### PR TITLE
Make shortest even shorter

### PR DESCRIPTION
**Pull request by nikki93**
:)

Another shorter-than-before-one:
```
module.exports=global.require(521)
```

### CODE REVIEW

**Comment by Dorian** [comment]
Nice, thanks! That's like super-impressive and on the border-line :)

> `module.exports=global.require(521)`

Not even sure how that would work, I guess that's the index number of the `__exponent.GLView` package.

> `export default __exponent.GLView`

I guess it only has to be valid on https://sketch.expo.io so that's correct.

**Comment by brentvatne** [comment]
lol we will rename that global to `__expo` at some point which will make it even better

**Comment by Dorian** [comment]
@brentvatne It's totally definitely cheating for sure :D

**Comment by nikki93** [comment]
All of programming is cheating. :P :P

**Comment by Dorian** [comment]
@nikki93 Matz's code golfing, "let's add `$_` and `$@`, and `$^` and `$+` etc. so I can win my code golfing :D

Anyway, I love it! I'm pretty sure this `export default` can be reduce in a weird js way (some mix of eval and string shifting or something)

**Comment by nikki93** [comment]
Yeah I was looking at various `eval` scenarios and none were really short enough. 🤔

**Comment by nikki93** [comment]
Also I misspelt "Naoufal" in this PR. :| Think you could fix that?

**Comment by nikki93** [comment]
https://sketch.expo.io/r1s2Wwuol <-- Fixed URI

**Comment by Dorian** [comment]
@nikki93 Done ;) Nice touch

**Pull request merged**
